version: 2

project_name: gitease

before:
  hooks:
    - go mod tidy

builds:
  - id: gitease
    main: ./main.go
    binary: gitease
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - id: archive
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: dinesh00509
    name: gitease
  footer: >-

    ---

    🚀 Released automatically by [GoReleaser](https://goreleaser.com).
